- name: Criar o comando de Join no Master Node
  become: yes
  hosts: master
  tasks:
    - name: Executar o comando para gerar o token
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Criar um Fact do comando de Join
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    
- name: Incluir os servidores Workers no cluster
  hosts: workers
  become: yes  
  tasks:
    - name: Incluindo o servidor no cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'] }}"